// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4JliC2pY71pWM3mOMJoBWx0S6Q-O0XBo',
    appId: '1:377491166081:web:edddf1fbbdaf6467d88e80',
    messagingSenderId: '377491166081',
    projectId: 'popup-deals-e1127',
    authDomain: 'popup-deals-e1127.firebaseapp.com',
    storageBucket: 'popup-deals-e1127.firebasestorage.app',
    measurementId: 'G-ZJ3FSR470E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFPax-a3xjjEK8oNBuylmkjAPAC_0IXT8',
    appId: '1:377491166081:android:3bdfc3ab0c03c088d88e80',
    messagingSenderId: '377491166081',
    projectId: 'popup-deals-e1127',
    storageBucket: 'popup-deals-e1127.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5Y7f0ehcdVmjoLPOBvvxcxxfGVhn7UGg',
    appId: '1:377491166081:ios:c5fe4466274ea217d88e80',
    messagingSenderId: '377491166081',
    projectId: 'popup-deals-e1127',
    storageBucket: 'popup-deals-e1127.firebasestorage.app',
    androidClientId: '377491166081-hrv0uho1nigdnp5tb9vbj8orjfet396r.apps.googleusercontent.com',
    iosClientId: '377491166081-bfmqrgm9vvjo9jccb1pfc0g1nvtrejv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.popupDealsApp',
  );
}
